# 1
name: Test

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Download reference captures
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/download-artifact@v4
        with:
          name: testScreenshots-main
          path: ${{ github.workspace }}/reference_captures/
        continue-on-error: true # Don't fail on 1st run when there's nothing

      - name: compare captures
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ./compare_captures.sh ${{ github.event.pull_request.number }} ${{ github.workspace }}/reference_captures/ ${{ github.workspace }}/build/captures/
