# 1
name: Test

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: compare captures
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./compare_captures.sh ${{ github.event.pull_request.number }} ${{ github.workspace }}/reference_captures/ ${{ github.workspace }}/build/captures/

      - name: upload diffs
        uses: actions/upload-artifact@v4
        with:
          name: artifact_diffs_pr_${{ github.event.pull_request.number }}
          path: ${{ github.workspace }}/build/captures/diffs/
