# 1
name: Upload reference screencaptures

on:
  pull_request: 
    branches: [ main ]
    types: [ closed ]

jobs:
  upload:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true

    if: github.event.pull_request.merged == true
    steps:
    - name: foo
      run: echo merged${{ github.event.pull_request.number }}
