# 1
name: Upload reference screencaptures

on:
  pull_request: 
    branches: [ main ]
    types: [ closed ]

jobs:
  upload:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true

    if: github.event.pull_request.merged == true
    steps:
    - name: Download reference captures from artifacts
      run: |
        wget https://github.com/iamsergio/test/releases/download/test_screen_captures/${{ github.event.pull_request.number }}-all-captures.tgz || exit 0
        mkdir captures
        tar xvf ${{ github.event.pull_request.number }}-all-captures.tgz -C captures --strip-components=1
    - name: Upload reference captures
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        if [ -d captures ]; then
          gh release upload reference_screen_captures-main captures/*.png --repo ${{ github.repository }}
        fi
